language: python
python: 3.6
before_install:
- sudo apt-get install -y binutils libproj-dev gdal-bin
install: pip install -r requirements.txt
script: python manage.py test --keepdb
deploy:
  provider: heroku
  api_key:
    secure: bXHG7gjLCNFeBu7wn1hz9V1w2H+XyKBKaNoUtEgLoCz/dKuONGv5/M57XResZnYTqG9Ca4PyQ4t2lVF62U8Q86/8s7cG2oGy206xoZDrQfXe1MoU5srgRpgUA70uJEnaBUfBVyts/ICvQoV8ENb/R449bJfa4IlYEDGaAoBXWYYB0oybgGD64vgzb5E2YVV2q//t/7OtxLefgKtkOQL8Nh0dOIFWQ05snGC085uJfLMMdskDPprkPzW2TRGxzEpYjYzzQRnhh2Q7WB8zRtu676T6bjUpfnSZ/51+NXh+ZSAKVZfy32BpbN4SopSuZE0ni5bDW8keo0zwMpfKL5h2bBy4SiZJ63iYSN3PpyjeCzlpASx48dwHCqLj+ZSTy0KJ7MOCJSIoClSIrPlO5kZqxqjCLCbmV48BXlzyAdOug9s3PsN5GCXvg6/8GjpdJ1Oq9m/xVcMn7ji3N4/3X8dYwNtBQWRiPbEacUHie+FAplrcnlGqoLXEsiyS5qLVTPEam/+zk5CJnUw5msZu5GM+3Yg23eSukYB1Tva5IKep3SjTUtpguueB+KJQc8OXkkZ9VJKch1+SEC52tV/NH7Hi7X8ORAPvDNnCPazQgNn76KP1UF3IZ51lZrQteZInFRfCJwMIBvhN6q46qd+g0zJ+kOfjp9fglFGzqlNlBkseNSM=
  app: feltp
  run:
  - python manage.py makemigrations
  - python manage.py migrate
  - heroku ps:scale web=1
  on: master
