language: python
python: 3.6
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- sudo apt-get install -y binutils libproj-dev gdal-bin
install: pip install -r requirements.txt
script: python manage.py test --keepdb
addons:
  ssh_known_hosts: "$DEPLOY_HOST"
before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo $TRAVIS_BUILD_DIR
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  script: rsync --rsync-path="sudo rsync" --quiet -rvz $TRAVIS_BUILD_DIR/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIR
  on:
    branch: master
  api_key: "$HEROKU_AUTH_TOKEN"
  
