language: python
python: 3.6
before_install:
- sudo apt-get install -y binutils libproj-dev gdal-bin
install: pip install -r requirements.txt
script: python manage.py test --keepdb
deploy:
  provider: heroku
  api_key:
    secure: 0g7wXYJ63R+r/E+bYBH68rB4KcZap/LFpNRLFMPIssj0fS46tM0xi1d9hFktsoLOYOTZLzcAHZvKu2EpAVHuD/oBFy+pBiiveko5cAT7L4Oa8ayFmmfykW90IVDxjGS7pn47swOARaZCvTihi12lVNGjZymKwgSgjsgixZzgD/OfNc+ZmUu5NuXfobP/1t9WGa/ni5TuCicCBbb6ixwcl/2srRRTWHsEeO1JVG6qqNRqWHK0169DnaBEYnD9eM73CGF7m9/h1em6Cd6bAdwrh4366budrBnxy4VASN8XZz8mx9e6vr1SiJm4m2SuKwI7jVaN1A8+vRJME137bY1cb5j5pEstPEGZsqh8yI+Mxt9hUn/Zens5vySnQX9Bt10j61qWSk3XvU1NXhF3lkyheVutDM6MlNGmL5qAHW3p8Mx2WkYjK8L8XSIdIw9XKiHEHkyQnwTeMXnPDTwGr6JmM9es3bJAyzGix0qAj3xEHPSUPVxHN6eQfrE9zik6qlQUenDVYAFHTfZX6rAs6FW7Oy/kqGWPfEuILFuoNX9Q6eNQ5wX/7VAbgegOwj6XNC5NFR1C/ZJnfkEkN+8gYHyUH9/amD2IYQNNB594FutMl30r/UygGNSw3VHLUzPBEo9puI/aBX9JZu9Y0EBQf+IsU0ivdnjEeDgMvhvF6BQEtLA=
  app: feltp
  run:
  - python manage.py makemigrations
  - python manage.py migrate
  - heroku ps:scale web=1
  on: master
