# Generated by Django 2.2.24 on 2021-07-23 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'district',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='api_images/events/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='api_images/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelOfHealthSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'level_of_health_system',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='verificationTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('used', 'used'), ('unused', 'unused')], default='unused', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verify_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone1', models.CharField(blank=True, max_length=13, null=True)),
                ('phone2', models.CharField(blank=True, max_length=13, null=True)),
                ('is_trained_frontline', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True)),
                ('cohort_number_frontline', models.IntegerField(blank=True, null=True)),
                ('yr_completed_frontline', models.DateField(blank=True, null=True)),
                ('institution_enrolled_at_frontline', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title_at_enroll_frontline', models.CharField(blank=True, max_length=100, null=True)),
                ('is_trained_intermediate', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True)),
                ('cohort_number_intermediate', models.IntegerField(blank=True, null=True)),
                ('yr_completed_intermediate', models.DateField(blank=True, null=True)),
                ('institution_enrolled_at_intermediate', models.CharField(blank=True, db_column='institution__enrolled_at_intermediate', max_length=100, null=True)),
                ('job_title_at_enroll_intermediate', models.CharField(blank=True, max_length=100, null=True)),
                ('is_trained_advanced', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True)),
                ('cohort_number_advanced', models.IntegerField(blank=True, null=True)),
                ('yr_completed_advanced', models.DateField(blank=True, null=True)),
                ('institution_enrolled_at_advanced', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title_at_enroll_advanced', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending approval', 'pending approval'), ('approved', 'approved'), ('registered', 'registered')], default='pending approval', max_length=20)),
                ('email_status', models.CharField(blank=True, default='not verified', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userprofile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='api_images/news/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='api_images/news/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='api_images/news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_to_user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_to_profile', to='apis.UserProfile')),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('is_current', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=5)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.District')),
                ('level_of_health_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.LevelOfHealthSystem')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.Region')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_to_user', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_to_profile', to='apis.UserProfile')),
            ],
            options={
                'db_table': 'jobinfo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_district', to='apis.Region'),
        ),
    ]
