# Generated by Django 2.2.24 on 2021-07-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_status',
        ),
    ]
