# Generated by Django 2.2.24 on 2021-07-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_userprofile_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_status',
            field=models.CharField(blank=True, default='not verified', max_length=100, null=True),
        ),
    ]
