# Generated by Django 2.2.24 on 2021-08-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='contactus',
            table='contactus',
        ),
    ]
