# Generated by Django 2.2.24 on 2021-08-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20210816_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'managed': True, 'verbose_name_plural': ' Contact Us'},
        ),
    ]
