# Generated by Django 2.2.24 on 2021-08-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20210819_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
