# Generated by Django 2.2.24 on 2021-08-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='api_images/profile/'),
        ),
    ]
