# Generated by Django 2.2.24 on 2021-08-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinfo',
            old_name='current_institution',
            new_name='_current_institution',
        ),
        migrations.RenameField(
            model_name='jobinfo',
            old_name='employment_status',
            new_name='_employment_status',
        ),
        migrations.RenameField(
            model_name='jobinfo',
            old_name='job_title',
            new_name='_job_title',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='_firstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='institution_enrolled_at_advanced',
            new_name='_institution_enrolled_at_advanced',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='institution_enrolled_at_frontline',
            new_name='_institution_enrolled_at_frontline',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='institution_enrolled_at_intermediate',
            new_name='_institution_enrolled_at_intermediate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_title_at_enroll_advanced',
            new_name='_job_title_at_enroll_advanced',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_title_at_enroll_frontline',
            new_name='_job_title_at_enroll_frontline',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='job_title_at_enroll_intermediate',
            new_name='_job_title_at_enroll_intermediate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone1',
            new_name='_phone1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone2',
            new_name='_phone2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='surname',
            new_name='_surname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='title',
            new_name='_title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_sex',
            field=models.CharField(db_column='sex', default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='_current_institution',
            field=models.CharField(blank=True, db_column='current_institution', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='_employment_status',
            field=models.CharField(blank=True, db_column='employment_status', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='_job_title',
            field=models.CharField(blank=True, db_column='job_title', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='is_current',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_firstname',
            field=models.CharField(db_column='firstname', default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_institution_enrolled_at_advanced',
            field=models.CharField(blank=True, db_column='institution_enrolled_at_advanced', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_institution_enrolled_at_frontline',
            field=models.CharField(blank=True, db_column='institution_enrolled_at_frontline', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_job_title_at_enroll_advanced',
            field=models.CharField(blank=True, db_column='job_title_at_enroll_advanced', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_job_title_at_enroll_frontline',
            field=models.CharField(blank=True, db_column='job_title_at_enroll_frontline', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_job_title_at_enroll_intermediate',
            field=models.CharField(blank=True, db_column='job_title_at_enroll_intermediate', default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_phone1',
            field=models.CharField(blank=True, db_column='phone1', default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_phone2',
            field=models.CharField(blank=True, db_column='phone2', default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_surname',
            field=models.CharField(db_column='surname', default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='_title',
            field=models.CharField(blank=True, db_column='title', default=None, max_length=10, null=True),
        ),
    ]
