# Generated by Django 2.2.24 on 2021-08-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20210823_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='_sex',
            field=models.CharField(db_column='sex', default=None, max_length=50, null=True),
        ),
    ]
