# Generated by Django 2.2.24 on 2021-08-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20210823_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobinfo',
            old_name='_current_institution',
            new_name='current_institution',
        ),
        migrations.RenameField(
            model_name='jobinfo',
            old_name='_employment_status',
            new_name='employment_status',
        ),
        migrations.RenameField(
            model_name='jobinfo',
            old_name='_job_title',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_institution_enrolled_at_advanced',
            new_name='institution_enrolled_at_advanced',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_institution_enrolled_at_frontline',
            new_name='institution_enrolled_at_frontline',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_institution_enrolled_at_intermediate',
            new_name='institution_enrolled_at_intermediate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_job_title_at_enroll_advanced',
            new_name='job_title_at_enroll_advanced',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_job_title_at_enroll_frontline',
            new_name='job_title_at_enroll_frontline',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_job_title_at_enroll_intermediate',
            new_name='job_title_at_enroll_intermediate',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_phone1',
            new_name='phone1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_phone2',
            new_name='phone2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_sex',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='_firstname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='_surname',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(db_column='firstname', default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(db_column='surname', default=None, max_length=50, null=True),
        ),
    ]
