# Generated by Django 2.2.24 on 2021-08-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20210823_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone1',
            field=models.CharField(blank=True, db_column='_phone1', default=None, max_length=13, null=True),
        ),
    ]
