# Generated by Django 2.2.24 on 2021-08-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20210823_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, db_column='firstname', default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone1',
            field=models.CharField(blank=True, db_column='phone1', default=None, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.CharField(blank=True, db_column='surname', default=None, max_length=50, null=True),
        ),
    ]
