# Generated by Django 2.2.24 on 2021-08-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20210824_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinfo',
            name='is_current',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_status',
            field=models.CharField(blank=True, default='not verified', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, db_column='sex', default=None, max_length=50, null=True),
        ),
    ]
