# Generated by Django 2.2.24 on 2021-09-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20210824_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='yr_completed_advanced',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='yr_completed_frontline',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='yr_completed_intermediate',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
