# Generated by Django 2.2.24 on 2021-10-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_auto_20210911_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='api_images/profile/')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.UserProfile')),
            ],
        ),
    ]
